package Common;

/**
* Common/ServerServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileServer.idl
* Saturday, August 24, 2019 10:21:54 o'clock PM EDT
*/

public final class ServerServantHolder implements org.omg.CORBA.portable.Streamable
{
  public Common.ServerServant value = null;

  public ServerServantHolder ()
  {
  }

  public ServerServantHolder (Common.ServerServant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Common.ServerServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Common.ServerServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Common.ServerServantHelper.type ();
  }

}
