package Common;


/**
* Common/ServerServantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileServer.idl
* Saturday, August 24, 2019 10:21:54 o'clock PM EDT
*/

abstract public class ServerServantHelper
{
  private static String  _id = "IDL:Common/ServerServant:1.0";

  public static void insert (org.omg.CORBA.Any a, Common.ServerServant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Common.ServerServant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Common.ServerServantHelper.id (), "ServerServant");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Common.ServerServant read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerServantStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Common.ServerServant value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Common.ServerServant narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Common.ServerServant)
      return (Common.ServerServant)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Common._ServerServantStub stub = new Common._ServerServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Common.ServerServant unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Common.ServerServant)
      return (Common.ServerServant)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Common._ServerServantStub stub = new Common._ServerServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
