package Common;


/**
* Common/ServerServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileServer.idl
* Saturday, August 24, 2019 10:21:54 o'clock PM EDT
*/

public interface ServerServantOperations 
{
  String login (String username, String hashedPassword);
  String registerUser (String username, String hashedPassword);
  String deleteUser (String username, String hashedPassword);
  void registerFiles (String username);
  void clearSharedFiles (String username);
  void clearNotSharedFiles (String username);
  String getUserFromPort (int port);
  int getConnectionPort (String username);
  String getConnectionAddress (String username);
  void setConnectionAddress (String username, String address);
  String[] viewAllSharedFiles ();
  String startFileShare (String username, String filename);
  String stopFileShare (String username, String filename);
  String[] findFile (String filename);
} // interface ServerServantOperations
